//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestSharpSample.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationSchemas {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationSchemas() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RestSharpSample.Resources.ValidationSchemas", typeof(ValidationSchemas).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {
        ///  &quot;definitions&quot;: {},
        ///  &quot;$schema&quot;: &quot;http://json-schema.org/draft-07/schema#&quot;,
        ///  &quot;$id&quot;: &quot;https://jsonschema.net/&quot;,
        ///  &quot;type&quot;: &quot;object&quot;,
        ///  &quot;title&quot;: &quot;PokeAPI endpoint pagination Schema&quot;,
        ///  &quot;required&quot;: [
        ///    &quot;count&quot;,
        ///    &quot;next&quot;,
        ///    &quot;previous&quot;,
        ///    &quot;results&quot;
        ///  ],
        ///  &quot;properties&quot;: {
        ///    &quot;count&quot;: {
        ///      &quot;$id&quot;: &quot;#/properties/count&quot;,
        ///      &quot;type&quot;: &quot;integer&quot;,
        ///      &quot;title&quot;: &quot;The Count Schema&quot;,
        ///      &quot;default&quot;: 0,
        ///      &quot;examples&quot;: [
        ///        365
        ///      ],
        ///      &quot;pattern&quot;: &quot;([0-9]*)&quot;
        ///    },
        ///    &quot; [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string apiPaginationjSchemaString {
            get {
                return ResourceManager.GetString("apiPaginationjSchemaString", resourceCulture);
            }
        }
    }
}
